# Generated by Django 4.0.2 on 2022-03-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_category_pid_alter_comment_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='pid',
            new_name='parents',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pid',
            new_name='parents',
        ),
    ]
