# Generated by Django 4.0.2 on 2022-03-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_pid_category_parents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='category_id',
            new_name='category',
        ),
    ]
