# Generated by Django 4.0.2 on 2022-03-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_category_id_board_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
