# Generated by Django 4.0.2 on 2022-03-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='password',
            field=models.CharField(max_length=225),
        ),
    ]
