# Generated by Django 4.0.2 on 2022-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
